#ifndef TAPE__EXAMPLE__DEL_HANDLER__DEL_HANDLER_H__INCLUDED_
#define TAPE__EXAMPLE__DEL_HANDLER__DEL_HANDLER_H__INCLUDED_

#include "module.h"

DECLARE_MODULE(del_handler);

#endif /* TAPE__EXAMPLE__DEL_HANDLER__DEL_HANDLER_H__INCLUDED_ */
