#ifndef TAPE__EXAMPLE__ADD_COMMAND__ADD_COMMAND_H__INCLUDED_
#define TAPE__EXAMPLE__ADD_COMMAND__ADD_COMMAND_H__INCLUDED_

#include "module.h"

DECLARE_MODULE(add_command);

#endif /* TAPE__EXAMPLE__ADD_COMMAND__ADD_COMMAND_H__INCLUDED_ */
