#ifndef TAPE__EXAMPLE__DEL_COMMAND__DEL_COMMAND_H__INCLUDED_
#define TAPE__EXAMPLE__DEL_COMMAND__DEL_COMMAND_H__INCLUDED_

#include "module.h"

DECLARE_MODULE(del_command);

#endif /* TAPE__EXAMPLE__DEL_COMMAND__DEL_COMMAND_H__INCLUDED_ */
