#ifndef TAPE__EXAMPLE__ADD_HANDLER__ADD_HANDLER_H__INCLUDED_
#define TAPE__EXAMPLE__ADD_HANDLER__ADD_HANDLER_H__INCLUDED_

#include "module.h"

DECLARE_MODULE(add_handler);

#endif /* TAPE__EXAMPLE__ADD_HANDLER__ADD_HANDLER_H__INCLUDED_ */
