#ifndef TAPE__EXAMPLE__DISPATCH__DISPATCH_H__INCLUDED_
#define TAPE__EXAMPLE__DISPATCH__DISPATCH_H__INCLUDED_

#include "module.h"

DECLARE_MODULE(dispatch);

#endif /* TAPE__EXAMPLE__DISPATCH__DISPATCH_H__INCLUDED_ */
